// Package chatstream is the per-chat SSE mechanism of spec.md 7.4.
//
// It exists separately from the global event bus (7.3) because that bus drops
// the oldest event when a subscriber falls behind, which is right for change
// notifications and wrong for token deltas (N2). Here nothing is dropped
// silently: each subscriber has a queue bounded by a byte budget, and a
// subscriber that exceeds it is sent an explicit `overflow` event and closed
// (N4), so the client refetches instead of showing a corrupted message.
//
// Every frame gets a monotonic per-run seq assigned at Publish (N5). The SSE
// event id is "{runId}:{seq}". A per-run ring buffer, kept until the run ends
// plus a grace period, lets a reconnecting client resume via Last-Event-ID.
package chatstream

import (
	"encoding/json"
	"errors"
	"io"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/AkosPapp/mcp-switchboard/hub/internal/agents"
)

var _ agents.Streamer = (*Hub)(nil)

// Frame types (N6) plus the two hub-generated ones.
const (
	TypeRunStarted       = "run_started"
	TypeDelta            = "delta"
	TypeToolCall         = "tool_call"
	TypeToolResult       = "tool_result"
	TypeApprovalRequired = "approval_required"
	TypeMessageDone      = "message_done"
	TypeRunDone          = "run_done"
	TypeError            = "error"
	// TypeOverflow is generated by the hub, never published. After it the
	// stream is closed and the client must refetch.
	TypeOverflow = "overflow"
)

// Overflow reasons.
const (
	ReasonSlowConsumer = "slow_consumer"
	ReasonEvicted      = "evicted"
	ReasonUnknownRun   = "unknown_run"
)

// Options tune the hub. Zero fields take the defaults.
type Options struct {
	// SubscriberBudget is the per-subscriber queue budget in bytes (default 1 MiB).
	SubscriberBudget int
	// RingFrames / RingBytes bound each run's resume buffer (defaults 8192 / 4 MiB).
	RingFrames int
	RingBytes  int
	// Grace is how long a run's ring outlives EndRun (default 2 minutes).
	Grace time.Duration
	// Keepalive is the SSE comment interval (default 15 s, N8).
	Keepalive time.Duration
}

func (o Options) withDefaults() Options {
	if o.SubscriberBudget <= 0 {
		o.SubscriberBudget = 1 << 20
	}
	if o.RingFrames <= 0 {
		o.RingFrames = 8192
	}
	if o.RingBytes <= 0 {
		o.RingBytes = 4 << 20
	}
	if o.Grace <= 0 {
		o.Grace = 2 * time.Minute
	}
	if o.Keepalive <= 0 {
		o.Keepalive = 15 * time.Second
	}
	return o
}

// Frame is one event on a chat stream.
type Frame struct {
	ChatID string
	RunID  string // empty for overflow
	Seq    int64  // 0 for overflow
	Type   string
	// Data is the JSON payload (an object).
	Data json.RawMessage
	// wire is the pre-rendered SSE text, shared by every subscriber.
	wire []byte
}

// ID is the SSE event id, "{runId}:{seq}"; empty for hub-generated frames.
func (f Frame) ID() string {
	if f.RunID == "" {
		return ""
	}
	return f.RunID + ":" + strconv.FormatInt(f.Seq, 10)
}

// Wire returns the frame as SSE text.
func (f Frame) Wire() []byte { return f.wire }

func newFrame(chatID, runID string, seq int64, typ string, payload map[string]json.RawMessage) Frame {
	if payload == nil {
		payload = map[string]json.RawMessage{}
	}
	set := func(k string, v any) {
		b, _ := json.Marshal(v)
		payload[k] = b
	}
	set("type", typ)
	if runID != "" {
		set("chatId", chatID)
		set("runId", runID)
		set("seq", seq)
	}
	data, _ := json.Marshal(payload)
	f := Frame{ChatID: chatID, RunID: runID, Seq: seq, Type: typ, Data: data}
	var sb strings.Builder
	if id := f.ID(); id != "" {
		sb.WriteString("id: " + id + "\n")
	}
	sb.WriteString("event: " + typ + "\n")
	sb.WriteString("data: ")
	sb.Write(data)
	sb.WriteString("\n\n")
	f.wire = []byte(sb.String())
	return f
}

func overflowFrame(chatID, reason string) Frame {
	return newFrame(chatID, "", 0, TypeOverflow, map[string]json.RawMessage{
		"reason": json.RawMessage(strconv.Quote(reason)),
	})
}

func toPayload(data any) map[string]json.RawMessage {
	raw, err := json.Marshal(data)
	if err != nil {
		return map[string]json.RawMessage{"data": json.RawMessage("null")}
	}
	var obj map[string]json.RawMessage
	if err := json.Unmarshal(raw, &obj); err == nil && obj != nil {
		return obj
	}
	return map[string]json.RawMessage{"data": raw}
}

// Hub fans frames out to per-chat subscribers.
type Hub struct {
	opts Options

	mu     sync.Mutex
	chats  map[string]*chatState
	closed bool

	subscribers atomic.Int64
}

type chatState struct {
	subs     map[*Subscription]struct{}
	runs     map[string]*runState
	runOrder []string
}

type runState struct {
	ring    []Frame // consecutive seqs, ring[0].Seq == first
	bytes   int
	nextSeq int64
	ended   bool
	timer   *time.Timer
}

// NewHub returns a hub with default options.
func NewHub() *Hub { return NewHubWithOptions(Options{}) }

// NewHubWithOptions returns a configured hub.
func NewHubWithOptions(o Options) *Hub {
	return &Hub{opts: o.withDefaults(), chats: map[string]*chatState{}}
}

// Subscribers is the number of open subscriptions, for the
// mcpsb_stream_clients{kind="chat"} gauge.
func (h *Hub) Subscribers() int { return int(h.subscribers.Load()) }

// Keepalive is the configured comment interval.
func (h *Hub) Keepalive() time.Duration { return h.opts.Keepalive }

func (h *Hub) chat(id string) *chatState {
	c := h.chats[id]
	if c == nil {
		c = &chatState{subs: map[*Subscription]struct{}{}, runs: map[string]*runState{}}
		h.chats[id] = c
	}
	return c
}

// Publish implements agents.Streamer. It assigns the run's next seq, retains
// the frame in the run's ring and offers it to every subscriber of the chat
// without ever blocking.
func (h *Hub) Publish(chatID, runID, frameType string, data any) {
	payload := toPayload(data)
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed {
		return
	}
	c := h.chat(chatID)
	r := c.runs[runID]
	if r == nil {
		r = &runState{nextSeq: 1}
		c.runs[runID] = r
		c.runOrder = append(c.runOrder, runID)
	}
	if r.ended {
		return
	}
	f := newFrame(chatID, runID, r.nextSeq, frameType, payload)
	r.nextSeq++
	r.ring = append(r.ring, f)
	r.bytes += len(f.wire)
	for (len(r.ring) > h.opts.RingFrames || r.bytes > h.opts.RingBytes) && len(r.ring) > 1 {
		r.bytes -= len(r.ring[0].wire)
		r.ring[0] = Frame{}
		r.ring = r.ring[1:]
	}
	for s := range c.subs {
		s.offer(f)
	}
}

// EndRun implements agents.Streamer: the ring is released after the grace period.
func (h *Hub) EndRun(chatID, runID string) {
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed {
		return
	}
	c := h.chats[chatID]
	if c == nil {
		return
	}
	r := c.runs[runID]
	if r == nil || r.ended {
		return
	}
	r.ended = true
	r.timer = time.AfterFunc(h.opts.Grace, func() { h.purgeRun(chatID, runID) })
}

func (h *Hub) purgeRun(chatID, runID string) {
	h.mu.Lock()
	defer h.mu.Unlock()
	c := h.chats[chatID]
	if c == nil {
		return
	}
	delete(c.runs, runID)
	for i, id := range c.runOrder {
		if id == runID {
			c.runOrder = append(c.runOrder[:i], c.runOrder[i+1:]...)
			break
		}
	}
	h.gcChat(chatID, c)
}

func (h *Hub) gcChat(chatID string, c *chatState) {
	if len(c.subs) == 0 && len(c.runs) == 0 {
		delete(h.chats, chatID)
	}
}

// Close ends every subscription and stops timers. Later Publish calls are no-ops.
func (h *Hub) Close() {
	h.mu.Lock()
	defer h.mu.Unlock()
	h.closed = true
	for _, c := range h.chats {
		for _, r := range c.runs {
			if r.timer != nil {
				r.timer.Stop()
			}
		}
		for s := range c.subs {
			s.closeAfterDrain()
		}
	}
	h.chats = map[string]*chatState{}
}

// Subscribe attaches to a chat's stream. lastEventID is "" for a live-only
// subscription, or the "{runId}:{seq}" of the last frame the client saw: the
// backlog after it is queued first (N5). When it cannot be honoured the
// subscription starts with an overflow frame and then ends.
func (h *Hub) Subscribe(chatID, lastEventID string) *Subscription {
	s := &Subscription{
		hub: h, chatID: chatID,
		budget: h.opts.SubscriberBudget,
		notify: make(chan struct{}, 1),
	}
	h.mu.Lock()
	defer h.mu.Unlock()
	if h.closed {
		s.closed = true
		return s
	}
	c := h.chat(chatID)
	if lastEventID != "" {
		if reason := h.replay(c, s, lastEventID); reason != "" {
			s.queue = []Frame{overflowFrame(chatID, reason)}
			s.queued = len(s.queue[0].wire)
			s.closed = true
			h.gcChat(chatID, c)
			return s
		}
	}
	c.subs[s] = struct{}{}
	h.subscribers.Add(1)
	s.attached = true
	return s
}

// replay queues the backlog after lastEventID; it returns an overflow reason
// when the position cannot be resumed.
func (h *Hub) replay(c *chatState, s *Subscription, lastEventID string) string {
	i := strings.LastIndexByte(lastEventID, ':')
	if i <= 0 {
		return ReasonUnknownRun
	}
	runID := lastEventID[:i]
	seq, err := strconv.ParseInt(lastEventID[i+1:], 10, 64)
	if err != nil || seq < 0 {
		return ReasonUnknownRun
	}
	r := c.runs[runID]
	if r == nil {
		return ReasonUnknownRun
	}
	if seq >= r.nextSeq {
		return ReasonUnknownRun
	}
	if len(r.ring) > 0 && seq+1 < r.ring[0].Seq {
		return ReasonEvicted
	}
	start := false
	for _, id := range c.runOrder {
		rs := c.runs[id]
		if rs == nil {
			continue
		}
		if id == runID {
			start = true
			for _, f := range rs.ring {
				if f.Seq > seq {
					s.offer(f)
				}
			}
			continue
		}
		if !start {
			continue
		}
		// A later run on this chat: everything of it, or a hole.
		if len(rs.ring) > 0 && rs.ring[0].Seq > 1 {
			return ReasonEvicted
		}
		for _, f := range rs.ring {
			s.offer(f)
		}
	}
	return ""
}

// ErrIdle is returned by Next when nothing arrived within the idle interval.
var ErrIdle = errors.New("chatstream: idle")

// Subscription is one client's view of a chat stream.
type Subscription struct {
	hub    *Hub
	chatID string
	budget int
	notify chan struct{}

	mu       sync.Mutex
	queue    []Frame
	queued   int
	closed   bool // no more frames will be queued; EOF after the queue drains
	attached bool
}

// offer queues f or, past the byte budget, replaces the queue by an overflow
// frame and closes. It never blocks. Called with the hub lock held.
func (s *Subscription) offer(f Frame) {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.closed {
		return
	}
	if s.queued+len(f.wire) > s.budget {
		o := overflowFrame(s.chatID, ReasonSlowConsumer)
		s.queue = []Frame{o}
		s.queued = len(o.wire)
		s.closed = true
	} else {
		s.queue = append(s.queue, f)
		s.queued += len(f.wire)
	}
	select {
	case s.notify <- struct{}{}:
	default:
	}
}

func (s *Subscription) closeAfterDrain() {
	s.mu.Lock()
	s.closed = true
	s.mu.Unlock()
	select {
	case s.notify <- struct{}{}:
	default:
	}
}

// Next returns the next frame. It returns ErrIdle after idle with nothing to
// deliver (idle <= 0 disables that), ctx.Err() when ctx ends, and io.EOF once
// the subscription is closed and drained (an overflow frame is delivered
// before that).
func (s *Subscription) Next(done <-chan struct{}, idle time.Duration) (Frame, error) {
	var timer *time.Timer
	var timeout <-chan time.Time
	if idle > 0 {
		timer = time.NewTimer(idle)
		defer timer.Stop()
		timeout = timer.C
	}
	for {
		s.mu.Lock()
		if len(s.queue) > 0 {
			f := s.queue[0]
			s.queue[0] = Frame{}
			s.queue = s.queue[1:]
			s.queued -= len(f.wire)
			s.mu.Unlock()
			return f, nil
		}
		closed := s.closed
		s.mu.Unlock()
		if closed {
			return Frame{}, io.EOF
		}
		select {
		case <-s.notify:
		case <-done:
			return Frame{}, errors.New("chatstream: canceled")
		case <-timeout:
			return Frame{}, ErrIdle
		}
	}
}

// Close detaches the subscription. Safe to call more than once.
func (s *Subscription) Close() {
	h := s.hub
	h.mu.Lock()
	if s.attached {
		s.attached = false
		h.subscribers.Add(-1)
		if c := h.chats[s.chatID]; c != nil {
			delete(c.subs, s)
			h.gcChat(s.chatID, c)
		}
	}
	h.mu.Unlock()
	s.mu.Lock()
	s.closed = true
	s.queue, s.queued = nil, 0
	s.mu.Unlock()
}
